app/controllers/bookings_controller.rb, app/models/drink.rb, app/views/static_pages/home.html.erb
Add 27137d6 and d47a482 to master.
=> Develop into master

app/assets/stylesheets/static_pages.scss, app/views/bookings/_form.html.erb
* Add placeholder to booking date
* Avoid overwriting the booking's email
=> Minor improvements to bookings

app/controllers/bookings_controller.rb
=> Don't display public bookings in the list of bookings

app/controllers/users_controller.rb
The destroy function was commented away. Works now.
fixes #49
=> Fixed the functionality for deleting users.

app/assets/javascripts/angular/controller/calendarCtrl.js
This fixes #58 regarding bookings the 10th of each month.
=> Adjust if statement in booking js

.travis.yml, app/views/bookings/index.html.erb
Simple use of bootstrap classes to remove information on mobile view.
Removed the possibility to confirm on this view since the admin doesn't get all information. Therefore admin have to click on show to then confirm
=> Fix for admin booking view

app/assets/javascripts/angular/controller/DrinksCtrl.coffee, app/controllers/drink_types_controller.rb, app/views/drink_types/_form.html.erb, app/views/drink_types/index.html.erb, app/views/drink_types/index.json.jbuilder, app/views/drink_types/show.html.erb, config/application.rb, config/locales/sv.yml, db/migrate/20160210172440_add_description_to_drink_types.rb, db/schema.rb
This add drink type descriptions and adds the brewery to the public drink list.
=> Drink type description

app/assets/javascripts/angular/controller/AdminDrinksCtrl.coffee
This should fix injection warnings plz merge fast :)
=> closes #102 by providing $http to beerinfo service

.mention-bot
=> Changed capitlal L in blacklist

config/initializers/devise.rb
The initializer for Devise was incorrectly written
=> Fix #115 incorrect devise initializer

app/controllers/news_controller.rb
The last updated news is at the top instead of the bottom, fixes #114
=> News are ordered with the latest at the top

.travis.yml, Dockerfile, Gemfile, Gemfile.lock, README.md, config/database.yml, config/environments/development.rb, config/routes.rb, docker-compose.yml
=> Add docker files, use Ruby 2.3.1, close #126

.rubocop.yml, app/controllers/news_controller.rb, app/controllers/static_pages_controller.rb, config/initializers/devise.rb
=> Add RuboCop config and fixes

Dockerfile, README.md, docker-compose.yml
This improves the build speed of the docker machine.
http://bradgessler.com/articles/docker-bundler/
=> Add bundler cache to docker files

app/views/booking_mailer/booking_received_board.html.erb, config/routes.rb
This changes the public url endpoints to Swedish for the booking thingies.
=> Rename booking route, fix #110

.travis.yml
=> Fix heroku auth key in .travis.yml

app/models/ability.rb
This appears to solve the issue `NoMethodError (undefined method `User' for #<Ability:0x007f7c2c4c0e00>)`
=> Add potential ability bug fix

app/controllers/static_pages_controller.rb
=> Allow unauthorized calls to letsencrypt endpoint

.coveralls.yml, .rubocop.yml, .travis.yml, Gemfile, Gemfile.lock, README.md, app/helpers/application_helper.rb, lib/tasks/brakeman.rake, lib/tasks/rubocop.rake, test/test_helper.rb
~~Based on #140, merge that first.~~
This adds RuboCop and [Brakeman](https://github.com/presidentbeef/brakeman) to the Travis scripts. Also, Coveralls is added.
=> Add Brakeman, Rubocop and Coveralls to CI

app/views/drink_types/index.json.jbuilder
got lost in a merge :innocent:
=> Added missing parameter
